#!/usr/bin/env bash
#
# This is the configuration file for the daps2docker package
#
# This is the default configuration. To create a specific user configuration,
# follow these steps:
#
# 1. Create a directory: mkdir -p ~/.config/daps2docker/
# 2. Copy this file to your config dir:
#    cp /etc/daps2docker/daps2docker.config ~/.config/daps2docker/
# 3. Remove the valid_formats variable, in most cases you don't need it
#    unless you want to configure a specific option.
#    If you really want to change some options, add a line into your
#    user config like this:
#    valid_formats["html"]="... your new options ..."
# 5. Save the file.
#
# For the moment, we support only a few options, namely:
# * those that do not require extra parameters like file names, to simplify
#   handling (FIXME...)
# * those that we can support (e.g. pdf --formatter=xep won't work, because xep
#   is not part of the container)
# * XSLT parameters are supported separately -> excluded
# * --help does not generate a document -> excluded

# declare -A valid_formats
valid_formats=(\
  ["bigfile"]="--novalid --norefcheck" \
  ["epub"]="--norefcheck" \
  ["html"]="--draft --meta --norefcheck --nostatic --remarks" \
  ["online-docs"]="--noepub --nohtml --nopdf --noset --optipng" \
  ["pdf"]="--draft --grayscale --meta --norefcheck --remarks" \
  ["package-html"]="--desktopfiles --documentfiles --pagefiles --single" \
  ["package-pdf"]="--desktopfiles --documentfiles --grayscale --pagefiles" \
  ["package-src"]="--locdrop --optipng" \
  ["single-html"]="--draft --meta --norefcheck --nostatic --remarks" \
  ["text"]="--ignore-styleroot --norefcheck" \
  ["webhelp"]="--draft --norefcheck --nosearch --nostatic --remarks" \
  ["validate"]="" \
  )

# The formats to build
# Supported formats: html online-docs pdf package-html webhelp
#                    single-html text epub package-pdf package-src bigfile
formats="validate,bigfile,html,pdf"

# The default container engine used
# Supported values: podman, docker (default "docker")
container_engine="docker"

# The default container to use
containername="registry.opensuse.org/documentation/containers/15.6/opensuse-daps-toolchain:latest"
